config/routes.rb
Rails.application.routes.draw do
  root 'base#home'
  get '/about', to: 'base#about'
  get '/prices', to: 'base#prices'
  resources :contacts, only: [:new, :create]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  def home
  end

  def about
  end

  def prices
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    data = {
      contact:{
        email: params[:contact][:email]
      }
    }
    data = data.to_json
    visitor_id = params[:visitor_id].first

    url = get_url visitor_id
    response = Typhoeus::Request.post(url,
      body: data,
      headers: { 'Accept' => 'application/json', 'Content-Type' => 'application/json' })
    response_data = JSON.parse(response.body, symbolize_names: true)

    if response.success?
      flash[:success] = 'Contact has been saved!'
      redirect_to root_path
    else
      @contact = Contact.new
      flash[:danger] = 'Invalid Email or already in use.'
      render 'new'
    end
  end

  private
  def get_url visitor_id
    if ENV['RAILS_ENV'] == 'development'
      "http://localhost:3000/visitors/#{visitor_id}/contacts"
    else
      "http://user-tracker.herokuapp.com/visitors/#{visitor_id}/contacts"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/base/about.html.haml
%h1 About Us
%hr
%h3
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Nunc vestibulum purus in rhoncus tincidunt. Curabitur turpis diam,
  tristique eget luctus at, lacinia eget tellus. Sed fermentum nibh vel
  aliquam viverra. Suspendisse iaculis lorem quis mauris pharetra imperdiet.
  Sed vehicula felis tellus, et porta quam sollicitudin nec. Cras consectetur
  elementum nisl, ut condimentum mi vestibulum at. Nunc in pharetra tortor.

app/views/base/home.html.haml
.jumbotron
  %h1
    Hello, dear!
  %hr
  %center
    = image_tag("dog.png", style:'height:auto;width:70%;')

app/views/base/prices.html.haml
%h2 See our prices below:
%br
%table{class: 'table'}
  %thead
    %tr
      %th Service
      %th Price
  %tbody
    %tr
      %td Nulla dignissim erat eu semper tincidunt
      %td $200,00
    %tr
      %td Duis id augue sed magna malesuada blandit eu et metus
      %td $320,00
    %tr
      %td Curabitur vulputate magna id tellus euismod commodo
      %td $282,00
    %tr
      %td Ut at tortor fringilla, commodo neque ac, lobortis est
      %td $220,00
    %tr
      %td Sed faucibus neque a molestie vestibulum
      %td $430,00
    %tr
      %td Nunc sagittis turpis non metus faucibus, at fermentum nisi molestie
      %td $190,00
    %tr
      %td Sed rutrum augue eget felis euismod pellentesque non at sapien
      %td $900,00
    %tr
      %td Praesent facilisis felis fringilla turpis semper ultricies
      %td $230,00
    %tr
      %td Aenean dignissim mauris sit amet sem condimentum venenatis
      %td $400,00
    %tr
      %td Cras quis lectus consectetur, varius ligula quis, fermentum diam
      %td $250,00

app/views/contacts/new.html.haml
%h3 Hello ! Send your email to us for more informations!
.row
  .col-md-6
    %br
    = form_for @contact, html: { multipart: true, role: 'form' }  do |f|
      = f.label :email
      = f.text_field :email, required: true, class: 'form-control'
      = hidden_field :visitor_id, ''
      %br
      = f.button 'Create Contact', class: 'btn btn-primary pull-right', type: :submit

%script{type: 'text/javascript'}
  setVisitorUidOnForm()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RD - Site Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="nav container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Site Example</a>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= controller.class == BaseController and controller.action_name == 'home' ? 'active' : '' %>">
            <%= link_to "Home", root_path %>
          </li>
          <li class="<%= controller.class == BaseController and controller.action_name == 'about' ? 'active' : '' %>">
            <%= link_to "About", about_path %>
          </li>
          <li class="<%= controller.class == BaseController and controller.action_name == 'prices' ? 'active' : '' %>">
            <%= link_to "Prices", prices_path %>
          </li>
          <li class="<%= controller.class == ContactsController and controller.action_name == 'new' ? 'active' : '' %>">
            <%= link_to "Contact", new_contact_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class='content'>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>